### ISSUE TITLE
fix /me in channels

### ISSUE THREAD

**Issue by Stjerneklar** [BNolet/RLC#28]
broke it removing channel names

**Comment by kretenkobr2** [comment]
I did some field testing... here are the results:

What I noticed is that "%general/me test" does indeed send "/me test" in the channel, but it does not do anything, the message is not _italics_, it is as if though /me isn't on the start of the message there... Then I tested "/me%general test" and it shows "Kretenkobr2%general test", but it is not in the channel, as if though %general isn't at the start of the message... Using autochannels renders the same result as the second test... I think the problem is that:

1) in the first example it printed out "/me", which means that it did not ignore "%general" although it fully did it's job - this would be fixed by making /me ignore channels before itself, or by making channelname be deleted after it does it's job of channeling... As it is not read by TTS, we should make it not be read by /me or be deleted from message when message is put into a channel...

2) autochannels wouldn't be fixed with the first approach because /me is counted first in using autochannels... but we can use the same analogy... we can make channels ignore /me before them, or make it be deleted from messages, but I think the username that comes there is a problem, and therefore we should make autochannels first use channel, and then use /me... right now it is the other way around...

I hope this helps you solve the problem, I don't know javascript so I cannot fix any code or do anything really, just field testing and deduction... This is just my observation(I have quite some C experience but I don't know javascript, so I know how program works in a nutshell, but not the language)...

**Comment by Stjerneklar** [comment]
thanks for the help kret, finaly decided to just check for /me both places.

Fixed in 3.10 :)
